name: dutypay
description: "DutyPay app"
publish_to: 'none'

version: 1.0.9+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  syncfusion_flutter_pdf: ^33.1.45
    
  firebase_core: ^4.2.1
  firebase_analytics: ^12.0.4

  # STORAGE
  shared_preferences: ^2.2.2

  # FILE SYSTEM (EXPORT/IMPORT)
  file_picker: ^8.0.0
  path_provider: ^2.1.2
  cloud_firestore: ^6.6.0
  uuid: ^4.5.3
  firebase_crashlytics: ^5.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/demo_payslips/
    - assets/icons/dutypay_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/dutypay_icon.png"
  remove_alpha_ios: true

  adaptive_icon_background: "#0B1F4D"
  adaptive_icon_foreground: "assets/icons/dutypay_icon.png"